language: generic
sudo: required
services:
- docker
script:
- docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/build.sh armhf"
before_deploy:
- .travis/decrypt.sh
deploy:
- provider: releases
  skip_cleanup: true
  file: "*.snap"
  file_glob: true
  api_key:
    secure: ZOEdmbeHco5fXMksA55tHNIc5vWbq9xbIT39L8GNkxbv6Z1nyRDnbMfP7fdAL1GtlkMzX9DXsmzQYyu0q0Jbjwhy97oYwCLb1jTFwTWkDRe9xyh16/yy2OErn3l7TT1CpTGWd2Rm00cbAzF4r/vY4lZFBHcj3BMyo/had1BgB38kjienPujA0yXLsbQgcIPA8xrLDH3DF75kDplpU5R49SDdUKFwLYij/AdCncVeqzXk93aPi2F4BgtAgn5ifKSumE4wO8qFTqH81l8CactpJVF2E15bKifcb6ZYAe3hcp9ifzujpy//Ug2NClsPDzhNDGCuqEgAjDhmkN2K5Vd90Q64U69m1h00ieC5xtSRHbjzWzvW9gMsrV27KTM1foCHlSx3HEGz0mVSbutAAESFXJG4UFn2WR4t5NJ9hwwq4yqJhS5bjVt8Eg1nuBCFS/nynk+3T8Jn0z7Js5xBjR0aQxpLeIrMjSmJ4gDlE+Ghh1RwMjnOFkYeM2A6eOM6uS6yRdnwJVVhse1vipOrMD7oEoNVl+osWZg2ydpiIDmXraNwDbmO79awZImInua3cs0dBenzhCrZVtWuBTsCHXuYeyQmzPp+cGoxZu2HvVxg5kE1BLlBEVAgxUuuORYwPE3pJ1ikrvwZEGuv248cadYF5xPt8rysJE0X8p2VMmRl+sA=
  on:
    repo: fuzeman/sunxi-kernel
    tags: true
- provider: script
  skip_cleanup: true
  script:
  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh $TRAVIS_TAG"
  on:
    repo: fuzeman/sunxi-kernel
    tags: true
#- provider: script
#  skip_cleanup: true
#  script:
#  - docker run -v $(pwd):$(pwd) -t ubuntu:yakkety sh -c "cd $(pwd) && .travis/push.sh"
#  on:
#    repo: fuzeman/sunxi-kernel
#    branch: master
